---

- hosts: localhost
  gather_facts: false
  vars:
    openshift_host: 'https://kubernetes.default'
    openshift_skip_tls_verify: '{{ skip_tls_verify | default(false) | bool }}'
    enable_dangerous_logs: false
    recommended_resources: true
  tasks:
    - when: admin_api_token is not defined
      no_log: '{{ not enable_dangerous_logs }}'
      block:
      - name: read token for current user
        command: oc whoami -t
        register: token
      - name: Set openshift_token to current user token
        set_fact:
          openshift_token: '{{ token.stdout }}'

    - name: set openshift_token to provided token
      set_fact:
        openshift_token: '{{ admin_api_token }}'
      no_log: '{{ not enable_dangerous_logs }}'
      when: admin_api_token is defined

    - name: Get name of current user
      command: oc whoami
      register: user

    - name: Set facts for variables that cannot be defined if they are not set
      set_fact:
        '{{ item.name }}': '{{ item.value }}'
      when: item.value
      with_items:
        - name: pg_hostname
          value: '{{ lookup("env", "DB_HOST") | default(awx_postgresql_hostname, true) | default(none) }}'
        - name: web_mem_request
          value: '{{ 0 if not recommended_resources else none }}'
        - name: web_cpu_request
          value: '{{ 0 if not recommended_resources else none }}'
        - name: task_mem_request
          value: '{{ 1 if not recommended_resources else none }}'
        - name: task_cpu_request
          value: '{{ 1000 if not recommended_resources else none }}'
        - name: rabbitmq_mem_request
          value: '{{ 0 if not recommended_resources else none }}'
        - name: rabbitmq_cpu_request
          value: '{{ 0 if not recommended_resources else none }}'
        - name: memcached_mem_request
          value: '{{ 0 if not recommended_resources else none }}'
        - name: memcached_cpu_request
          value: '{{ 0 if not recommended_resources else none }}'

- import_playbook: /usr/share/awx_installer/installer/install.yml
  vars:
    pg_database: '{{ lookup("env", "DB_NAME") | default(awx_postgresql_dbname, true) | default("awx") }}'
    pg_username: '{{ lookup("env", "DB_USER") | default(awx_postgresql_user, true) | default("awx") }}'
    pg_password: '{{ lookup("env", "DB_PASSWORD") | default(awx_postgresql_password, true) | default("awxpassword") }}'
    pg_port: '{{ lookup("env", "DB_PORT") | default(awx_postgresql_port, true) | default(5432) }}'
    dockerhub_base: '{{ awx_image_org | default("ansible") }}'
    dockerhub_version: '{{ awx_image_tag | default("latest") }}'
    pg_volume_capacity: '{{ awx_postgresql_volume_capacity | default("5", true) }}'
    openshift_host: 'https://kubernetes.default'
    openshift_user: '{{ user.stdout }}'
    openshift_skip_tls_verify: '{{ skip_tls_verify | default(false) | bool }}'
    openshift_pg_emptydir: '{{ postgresql_emptydir | default(false) | bool }}'
    openshift_project: '{{ namespace }}'
    awx_kubernetes_namespace: '{{ namespace }}'
