---

- hosts: localhost
  gather_facts: false
  vars:
    openshift_host: 'https://kubernetes.default'
    openshift_skip_tls_verify: '{{ skip_tls_verify | default(false) | bool }}'
    enable_dangerous_logs: false
  tasks:
    - when: admin_api_token is not defined
      no_log: '{{ not enable_dangerous_logs }}'
      block:
      - name: read token for current user
        command: oc whoami -t
        register: token
      - name: Set openshift_token to current user token
        set_fact:
          openshift_token: '{{ token.stdout }}'

    - name: set openshift_token to provided token
        set_fact:
        openshift_token: '{{ admin_api_token }}'
      no_log: '{{ not enable_dangerous_logs }}'
      when: admin_api_token is defined

    - name: Authenticate with OpenShift via token
      shell: |
        oc login {{ openshift_host }} \
          --token {{ openshift_token }} \
          --insecure-skip-tls-verify={{ openshift_skip_tls_verify | default(false) | bool }}
      no_log: '{{ not enable_dangerous_logs }}'

    - name: Get name of current user
      command: oc whoami
      register: user

    - name: Set facts for variables that cannot be defined if they are not set
      set_fact:
        pg_hostname: '{{ t_pg_host }}'
      when: t_pg_host
      vars:
        t_pg_host: '{{ lookup("env", "DB_HOST") | default(awx_postgresql_hostname, true) | default(None) }}'
    - name: Fix rolebindings for deployer
      k8s_raw:
        resource_definition:
          apiVersion: v1
          kind: RoleBinding
          metadata:
            name: system:deployers
            namespace: '{{ namespace }}'
          roleRef:
            name: system:deployer
            kind: ClusterRole
          subjects:
          - kind: ServiceAccount
            name: deployer
            namespace: '{{ namespace }}'
          userNames:
          - system:serviceaccount:{{ namespace }}:deployer


- import_playbook: /usr/share/awx_installer/installer/install.yml
  vars:
    pg_database: '{{ lookup("env", "DB_NAME") | default(awx_postgresql_dbname, true) | default("awx") }}'
    pg_username: '{{ lookup("env", "DB_USER") | default(awx_postgresql_user, true) | default("awx") }}'
    pg_password: '{{ lookup("env", "DB_PASSWORD") | default(awx_postgresql_password, true) | default("awxpassword") }}'
    pg_port: '{{ lookup("env", "DB_PORT") | default(awx_postgresql_port, true) | default(5432) }}'
    dockerhub_base: '{{ awx_image_org | default("ansible") }}'
    dockerhub_version: '{{ awx_image_tag | default("latest") }}'
    pg_volume_capacity: '{{ awx_postgresql_volume_capacity | default("5", true) }}'
    openshift_host: 'https://kubernetes.default'
    openshift_user: '{{ user.stdout }}'
    openshift_skip_tls_verify: '{{ skip_tls_verify | default(false) | bool }}'
    openshift_pg_emptydir: '{{ postgresql_emptydir | default(false) | bool }}'
    awx_openshift_project: '{{ namespace }}'
    awx_kubernetes_namespace: '{{ namespace }}'
